context:
  version: 2.1.0

package:
  name: licensor
  version: ${{ version }}

source:
  url: https://github.com/raftario/licensor/archive/v${{ version }}.tar.gz
  sha256: d061ce9fd26d58b0c6ababa7acdaf35222a4407f0b5ea9c4b78f6835527611fd

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - licensor --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Write licenses to stdout
  homepage: https://github.com/raftario/licensor
  repository: https://github.com/raftario/licensor

extra:
  recipe-maintainers:
    - danielnachun
